### ISSUE TITLE
instructions for .rbenv

### ISSUE THREAD

**Issue by gurgeous** [fohte/rubocop-daemon#7]
The daemon is amazing! It sped up my vscode autoformat from ~1s to <200ms. Huge difference in daily usage. Thanks for creating!

It would be great to add some instructions for rbenv too, since it can be a bit confusing. Here's what I did:

```sh
# which rubocop is rbenv running?
$ rbenv which rubocop
/Users/username/.rbenv/versions/2.5.1/bin/rubocop

# Override rubocop with a symlink to rubocop-daemon-wrapper
$ ln -fs /usr/local/bin/rubocop-daemon-wrapper $HOME/.rbenv/versions/2.5.1/bin/rubocop
```

**Comment by fohte** [comment]
Thanks @gurgeous! I've updated README.md (https://github.com/fohte/rubocop-daemon/commit/e72647d65c75d0e062a85a0b737bd8b6be12b894).
I hope it would be helpful for VS Code users!

**Comment by smlparry** [comment]
I had issues setting up my new M1 mac, not sure if that has anything to do with it, but I kept getting the following error:

```
~/C/f/fitter-pwa » rubocop                                                                                                                                                                                               
/opt/homebrew/Cellar/rbenv/1.2.0/libexec/rbenv-exec: line 47: /Users/samparry/.rbenv/versions/2.7.5/bin/rubocop: is a directory
/opt/homebrew/Cellar/rbenv/1.2.0/libexec/rbenv-exec: line 47: exec: /Users/samparry/.rbenv/versions/2.7.5/bin/rubocop: cannot execute: Undefined error: 0
```

I was able to fix it by changing the sym link, and running the following command (notice the extra `/rubocop` at the end of the first arg)

```
$ ln -fs /usr/local/bin/rubocop-daemon-wrapper/rubocop $HOME/.rbenv/versions/2.7.5/bin/rubocop 
```

Now its working as expected, not sure whats going on there

**Comment by padi** [comment]
@smlparry I encountered the same issue.

When VS Code tries to run `rubocop` (shim) and hands it off to rbenv, it ultimately tries to run a "folder" instead of code, which doesn't make sense, hence the error.

The error is what the error exactly says, the rubocop it's trying to run is linked to a folder (/usr/local/bin/rubocop-daemon-wrapper), when the intended purpose is to symlink to an executable. i.e.:

Expected symlink: `~/.rbenv/versions/3.1.1/bin/rubocop -> /usr/local/bin/rubocop-daemon-wrapper/rubocop`
Encountered symlink: `~/.rbenv/versions/3.1.1/bin/rubocop -> /usr/local/bin/rubocop-daemon-wrapper`

So you're right in fixing the symlink.

In my case, I just fixed the symlink in a one-liner:

```shell
ln -fs /usr/local/bin/rubocop-daemon-wrapper/rubocop $(rbenv which rubocop)
```
