### ISSUE TITLE
rubocop-daemon-wrapper removes escape characters if -s or --stdin args are present

### ISSUE THREAD

**Issue by ericmatte** [fohte/rubocop-daemon#8]
When formatting a file on VSCode using `rubocop-daemon-wrapper` with `ruby-rubocop`, all escape characters like `\t\r\n\a` are removed from the current `.rb` file.
They seems to get removed when reading stdin with `cat`: https://github.com/fohte/rubocop-daemon/blob/master/bin/rubocop-daemon-wrapper#L53.

Expected after auto-correct on save:
```
def something
  puts "Test \t\r\n\a"
rescue StandardError => e
  Rails.logger.error "Exception occurred :\n#{@message}"
end
```

Actual behavior:
```
def something
  puts "Test
"
rescue StandardError => e
  Rails.logger.error "Exception occurred :
#{@message}"
end
```

PS: The daemon is a must when using rubocop auto-correct! Thanks you very much.

**Comment by fohte** [comment]
Hi @ericmatte, thanks for reporting this issue!

I've fixed the issue in e7e517e092aab5ece4a400c5eaf81c8d976fa82c (PR #9).
This fix is already merged in master, so could you try this?

Please let me know if there are any problems :)

**Comment by gurgeous** [comment]
This seems like quite a scary bug, and I need to go through our commit logs to see if we accidentally broke something in a subtle way... Would it be possible to add a test for this edge case to prevent future occurrences?

**Comment by ericmatte** [comment]
Hi @fohte, thank you for your quick response. It works great!

**Comment by ericmatte** [comment]
And @gurgeous, on our side, it was mostly some `\n` in strings, which were converted to a real newline. But this remains a valid syntax for newline in Ruby strings.
So, as far as I'm know, there have been no side effects on our project.

That said, a simple test would surely be a good idea.

**Comment by fohte** [comment]
Hi @gurgeous,

I also think that adding a simple test for the rubocop-daemon-wrapper would improve maintainablity.

I was trying out to add some test cases with Bats, but they are complicated a little.
For example, we have to mock the rubocop-daemon server.
I think it would be complicated and difficult to maintain continuously.

Futhermore, with Bash, we have to handle slightly different commands for each OS, like `nc` (#5).

So instead, I'm planning to switch to write lightweight rubocop-daemon client in Go.

That issues would be resolved by writing in Go. Because it can support cross-platform easily, and easy to read.

**Comment by gurgeous** [comment]
Great! Just out of curiosity - have you considered rewriting rubocop-daemon in ruby? At our company we have a policy that we write all scripts (no matter how long or short) in Ruby. It's worked out quite well for our team.

**Comment by fohte** [comment]
I had not considered rewritting rubocop-daemon client in Ruby.
It sounds like a great idea for me, as a first step!

However, Go is faster than Ruby, so I would like to provide the client written in Go in the future.

I think you might know, the client is already implemented in rubocop-daemon gem (you can use `rubocop-daemon exec` command), but it is not easy to integrate with editor because its interface is different from `rubocop` command.

First of all, I'll try to reimplement the client in Ruby with same interface as `rubocop` command! :smile:
